# File: .github/workflows/repo-sync.yml
name: sync-stark666-scripts
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ main ]
  repository_dispatch:
    types: sync-stark666-scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/stark666
        with:
          persist-credentials: false

      - name: sync LXK9301-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/stark666/smzdm_bot.git"
          source_branch: "main"
          destination_branch: "master"
          github_token: ${{ secrets.PAT }}
